# Generated by Django 6.0.6 on 2026-07-01 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=200)),
                (
                    "avatar_image",
                    models.ImageField(blank=True, null=True, upload_to="author_images"),
                ),
                ("create_ad", models.DateTimeField(auto_now_add=True)),
                ("update_ad", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_book",
                    models.CharField(max_length=200, verbose_name="Название книги"),
                ),
                (
                    "type_skin",
                    models.CharField(
                        choices=[
                            ("HARD", "Твердый переплёт"),
                            ("SOFT", "Мягкий переплёт"),
                        ],
                        default="HARD",
                        max_length=4,
                        verbose_name="Переплёт",
                    ),
                ),
                (
                    "number_pages",
                    models.PositiveIntegerField(verbose_name="Кол-во страниц"),
                ),
                ("weight_book", models.PositiveIntegerField(verbose_name="Вес книги")),
                (
                    "year_publication",
                    models.PositiveIntegerField(verbose_name="Год книги"),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("HARD", "Твердый переплёт"),
                            ("SOFT", "Мягкий переплёт"),
                        ],
                        default="Sci-Fi",
                        max_length=9,
                        verbose_name="Жанр книги",
                    ),
                ),
                ("country", models.CharField(max_length=200, verbose_name="Страна")),
                (
                    "isbn",
                    models.CharField(max_length=50, verbose_name="Название книги"),
                ),
                (
                    "age_limit",
                    models.PositiveIntegerField(verbose_name="Возрастное ограничение"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images",
                        verbose_name="Обложка",
                    ),
                ),
                ("create_ad", models.DateTimeField(auto_now_add=True)),
                ("update_ad", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.author",
                        verbose_name="Автор",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssuingBookUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_ad", models.DateTimeField(auto_now_add=True)),
                ("update_ad", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Received", "Получил"),
                            ("Returned", "Вернул"),
                            ("Lost", "Утеряна"),
                            ("Spoiled", "Испорчена"),
                        ],
                        default="Received",
                        max_length=9,
                        verbose_name="Статус пользования",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
