# Generated by Django 6.0.6 on 2026-07-10 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=200, verbose_name="Ф.И.О автора"),
                ),
                (
                    "avatar_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="author_images",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "create_ad",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "update_ad",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_book",
                    models.CharField(max_length=200, verbose_name="Название книги"),
                ),
                (
                    "type_skin",
                    models.CharField(
                        choices=[
                            ("HARD", "Твердый переплёт"),
                            ("SOFT", "Мягкий переплёт"),
                        ],
                        default="HARD",
                        max_length=4,
                        verbose_name="Тип обложки",
                    ),
                ),
                (
                    "number_pages",
                    models.PositiveIntegerField(verbose_name="Кол-во страниц"),
                ),
                ("weight_book", models.PositiveIntegerField(verbose_name="Вес книги")),
                (
                    "year_publication",
                    models.PositiveIntegerField(verbose_name="Год книги"),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Horror", "Ужасы"),
                            ("Comedy", "Коммедия"),
                            ("Sci-Fi", "Фантастика"),
                            ("Animation", "Мульфильмы"),
                            ("Drama", "Драма"),
                        ],
                        default="Sci-Fi",
                        max_length=9,
                        verbose_name="Жанр книги",
                    ),
                ),
                ("country", models.CharField(max_length=200, verbose_name="Страна")),
                (
                    "isbn",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Уникальный ISBN"
                    ),
                ),
                (
                    "age_limit",
                    models.PositiveIntegerField(verbose_name="Возрастное ограничение"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images",
                        verbose_name="Обложка",
                    ),
                ),
                ("create_ad", models.DateTimeField(auto_now_add=True)),
                ("update_ad", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.author",
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
        migrations.CreateModel(
            name="IssuingBookUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_ad", models.DateTimeField(auto_now_add=True)),
                ("update_ad", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Received", "Получил"),
                            ("Returned", "Вернул"),
                            ("Lost", "Утеряна"),
                            ("Spoiled", "Испорчена"),
                        ],
                        default="Received",
                        max_length=9,
                        verbose_name="Статус пользования",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
            ],
        ),
    ]
