# Generated by Django 6.0.6 on 2026-07-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Horror", "Ужасы"),
                    ("Comedy", "Коммедия"),
                    ("Sci-Fi", "Фантастика"),
                    ("Animation", "Мульфильмы"),
                    ("Drama", "Драма"),
                ],
                default="Sci-Fi",
                max_length=9,
                verbose_name="Жанр книги",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="type_skin",
            field=models.CharField(
                choices=[("HARD", "Твердый переплёт"), ("SOFT", "Мягкий переплёт")],
                default="HARD",
                max_length=4,
                verbose_name="Тип обложки",
            ),
        ),
    ]
