# Generated by Django 6.0.6 on 2026-07-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_genre_alter_book_type_skin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="avatar_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="author_images", verbose_name="Фото"
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="create_ad",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="author",
            name="fullname",
            field=models.CharField(max_length=200, verbose_name="Ф.И.О автора"),
        ),
        migrations.AlterField(
            model_name="author",
            name="update_ad",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
