# Generated by Django 6.0.6 on 2026-07-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_author_avatar_image_alter_author_create_ad_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Автор", "verbose_name_plural": "Авторы"},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "Книга", "verbose_name_plural": "Книги"},
        ),
    ]
