# Generated by Django 6.0.6 on 2026-07-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_author_options_alter_book_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=50, verbose_name="Уникальный ISBN"),
        ),
    ]
